# Generated by Django 4.1.7 on 2023-05-01 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=60)),
                ('title2', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='upload/products')),
            ],
        ),
    ]
