# Generated by Django 4.1.7 on 2023-05-01 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product1_product2_product3_alter_banner_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product2',
        ),
        migrations.DeleteModel(
            name='Product3',
        ),
    ]
