# Generated by Django 4.1.7 on 2023-05-01 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_product2_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product2',
        ),
    ]
