# Generated by Django 4.1.7 on 2023-05-02 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_delete_banner2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
    ]
