# Generated by Django 4.1.7 on 2023-05-04 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_staff'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
