# Generated by Django 4.1.7 on 2023-05-04 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_product_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ribbon',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
