# Generated by Django 4.1.7 on 2023-05-04 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_product_ribbon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='selling_price',
        ),
        migrations.AddField(
            model_name='product',
            name='discounted_price',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
