# Generated by Django 4.1.7 on 2023-05-05 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_product_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discount_rate',
            new_name='product_detail_ribbon',
        ),
    ]
