# Generated by Django 4.1.7 on 2023-05-05 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_rename_discount_rate_product_product_detail_ribbon'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image3',
            field=models.ImageField(blank=True, upload_to='photos/products'),
        ),
    ]
