# Generated by Django 4.1.7 on 2023-05-05 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_product_image4_product_image5_product_image6'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image3',
            field=models.ImageField(upload_to='photos/products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image4',
            field=models.ImageField(upload_to='photos/products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image5',
            field=models.ImageField(upload_to='photos/products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image6',
            field=models.ImageField(upload_to='photos/products'),
        ),
    ]
