# Generated by Django 4.2.1 on 2023-05-21 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='image4',
            field=models.ImageField(blank=True, upload_to='photos/sliders'),
        ),
    ]
