# Generated by Django 4.2.1 on 2023-05-21 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='link',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
