# Generated by Django 4.2.1 on 2023-09-02 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='prfile_picture',
            new_name='profile_picture',
        ),
    ]
