# Generated by Django 4.2.1 on 2023-05-12 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_variation'),
        ('carts', '0003_alter_cart_cart_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='variations',
            field=models.ManyToManyField(blank=True, to='app.variation'),
        ),
    ]
